version: 0.2

phases:
  build:
    commands:
      - echo Build phase startet ....
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/backendCamtougo.jar
  discard-paths: yes